### ISSUE TITLE
Nullptr error for fonts

### ISSUE THREAD

**Issue by NaiJii** [kwilcz/Antario#106]
This line in Font.cpp : 
`   tx->LockRect(0, &lockRect, nullptr, D3DLOCK_DISCARD); `

is nullptr, and it is also defined as a nullptr 2 lines above : 
`    IDirect3DTexture9* tx = nullptr;`

Did I misunderstood something or is it a bug ?

Thanks in advance.

**Comment by kwilcz** [comment]
Literally 1 line below nullptr definitio, texture is created and initialized.
