### ISSUE TITLE
weapon esp

### ISSUE THREAD

**Issue by heavenly** [kwilcz/Antario#11]
weapon esp big broke. just letting you know, will check it out later.

**Comment by Monsterxsync** [comment]
can confirm, doing anything with GetActiveWeapon causes game to crash.

**Comment by kwilcz** [comment]
I didn't test the changes to be fair, don't have access to csgo rn but after recent fixes it should be working properly.

**Comment by Monsterxsync** [comment]
yup the wep esp is working good now, the netvars are wrong with GetNextPrimaryAttack() also causes crashes, Fix: [https://pastebin.com/X38SNwtS](https://pastebin.com/X38SNwtS)

**Comment by certmemer** [comment]
fucking trash netvar manager pls remove @Wando1423

**Comment by kwilcz** [comment]
Fixed with: https://github.com/Wando1423/Antario/commit/13cd4c2867c48b9194f81da8aa69b22f2e0f5ce4 and https://github.com/Wando1423/Antario/commit/ee2f35d9da6741ec49fc124c56b12e4bb8f4a64b.
