### ISSUE TITLE
Game Crash in EnginePrediction

### ISSUE THREAD

**Issue by Monsterxsync** [kwilcz/Antario#13]
Line 50 Engine Prediction.cpp: g_pMovement->ProcessMovement(g::pLocalEntity, &data);

How to recreate;
1. The second you touch the water on de_overpass the game crashes.

might have something to do with movetype changing when you hit the water i'll have a look after work.

**Comment by certmemer** [comment]
no
[should be fine now](https://github.com/Wando1423/Antario/commit/6242f00729cadc2a788cbdc0766c77ef00439cd9)

**Comment by Monsterxsync** [comment]
Thanks ill try it out.
