### ISSUE TITLE
Few things after comboboxes / menu cleanup.

### ISSUE THREAD

**Issue by Monsterxsync** [kwilcz/Antario#14]
In Button::UpdateData(), you can hold the button and it will execute the function many times a second.
Fixed this by just making it a static bool that resets to false every time like it used to.

Also the combobox label doesnt show up anywhere?

Edit: you can click through the combobox options and press buttons ect.

Suggestion:
Is it possible to have scrolling in the comboboxes for things like this [https://puu.sh/z1oca/676dbe352e.jpg](https://puu.sh/z1oca/676dbe352e.jpg) , i Know i could just split it up into multiple comboboxes but just to make things easier.

**Comment by kwilcz** [comment]
Ye, sure. I will implement scrolling later on, after i'll be done with all the basic menu functions.

All the other fixes will be pushed somewhat later this / next week.

**Comment by Monsterxsync** [comment]
Awesome thanks.

**Comment by kwilcz** [comment]
Ok, for now:
Fixed button and combo behaviour to work like it should: https://github.com/Wando1423/Antario/commit/47d3fd407028f73ff48f2e82cb4df727ee339d74

Scrolling through comboboxes will be added as soon as i'll find more time. Same with label-drawing (kinda implemented in test branch but not tested at all).

**Comment by Monsterxsync** [comment]
Awesome, are you thinking of doing tabs anytime? Is there a way to have multiple windows?

**Comment by kwilcz** [comment]
Ye, you can have multiple windows, just create a new BaseWindow shared_ptr like do it with the actual one. It will have its proper position, child objects, etc.

About tabs, I'm not thinking about adding them for now. Maybe in a much later stage as I'd rather focus on my private projects.

**Comment by Monsterxsync** [comment]
This update completely broke the menu, if you change any option like checkboxes ect then drag the menu this happens.  [https://puu.sh/z8h6t/316538987a.jpg](https://puu.sh/z8h6t/316538987a.jpg)

**Comment by kwilcz** [comment]
Oh sheit, didnt think it would fuck up. Reverted and will test later on.

**Comment by Monsterxsync** [comment]
Are you planning on expanding the SDK to include the classes to do chams?

**Comment by kwilcz** [comment]
No, I'm adding only basics for the base. Everything else can and should be added by anyone trying to use it (and implement own features).

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/c0b0683349da33a20588c728cc1eb415cc93d39d

**Comment by Monsterxsync** [comment]
How would i go about making the comboboxes close when i select an item? if i just do:
 ` this->bIsActive = false;`  i get the problem where the items drag like before. The menu is fully working now so thats good :)

**Comment by kwilcz** [comment]
You have also to change the "hovered" state to negative (-1 would do) as its taken to account.
https://github.com/Wando1423/Antario/blob/master/Antario/Menu.cpp#L562

To keep items render always properly, you could set up a different function loop that takes care only about position setup and leave UpdateData as the mouse-hover etc option only.

**Comment by Monsterxsync** [comment]
```
if (this->mouseCursor->bLMBPressed && !this->bIsButtonHeld)
{
        *this->iCurrentValue = it;
	this->bIsButtonHeld = true;
	this->idHovered = -1;
	this->bIsActive = false; //Added so that the checkbox will close.
}
```

I tried doing this but this also doesn't work. is it because this->idHovered = it; gets called from mouse being in the combobox?

**Comment by kwilcz** [comment]
Move this line above your if statements, so the code you added will overwrite it:
https://github.com/Wando1423/Antario/blob/master/Antario/Menu.cpp#L545

**Comment by Monsterxsync** [comment]
Yeah i realised that after i posted thanks anyways (y) all working as it should.

**Comment by Monsterxsync** [comment]
I've just noticed after doing that if i click an option thats over a button/checkbox it will click through it.

**Comment by tiagorodrigues2** [comment]
when do you think you will be adding scrollbar to comboboxes?
