### ISSUE TITLE
Lastest Commit breaks buttons?

### ISSUE THREAD

**Issue by Monsterxsync** [kwilcz/Antario#20]
The buttons do not work at all after latest commit.

**Comment by ghost** [comment]
Seems to work perfectly for me, have you tried actually trying to figure out the problem?

**Comment by Monsterxsync** [comment]
I'll have another look when i get home but it wasbt working in my branch and the default one last night.

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/4ff8212e2d04dbd6977f5a195caffed674ef1339
Broke cus static.

**Comment by ghost** [comment]
Apologies for that, only use 1 button so didn't notice.
