### ISSUE TITLE
Only the first combobox works then all the others stay in place.

### ISSUE THREAD

**Issue by Monsterxsync** [kwilcz/Antario#21]
Don't have git on this computer so cant make a PR, but you fix it by doing 

[https://pastebin.com/rLgnFrMu](https://pastebin.com/rLgnFrMu)

**Comment by kwilcz** [comment]
Didn't notice while testing.
Fixed with https://github.com/Wando1423/Antario/commit/a9da4806dcb0e3f3519fedc92ec77beeac7cd453

**Comment by ghost** [comment]
FYI @Monsterxsync you can edit files in the browser and GitHub will automatically fork the repo, and allow you to make a PR. All from the web.

**Comment by Monsterxsync** [comment]
Oh i didnt know that thanks!
