### ISSUE TITLE
Use Templates for slider instead of defined type

### ISSUE THREAD

**Issue by ghost** [kwilcz/Antario#25]
https://github.com/L-KE/FAKEWARE/blob/master/cheat/Menu/GUI.h#L116

Just an idea.

**Comment by kwilcz** [comment]
Oh ye, forgot about templates. Will do 👍

**Comment by lukeramsden** [comment]
Closed by 917aeb7cb5c0a9c46b8dcc246c07f5172c10fc34

**Comment by ghost** [comment]
Closed by 917aeb7cb5c0a9c46b8dcc246c07f5172c10fc34
