### ISSUE TITLE
Closing game while cheat is injected cause game to not exit properly

### ISSUE THREAD

**Issue by ghost** [kwilcz/Antario#28]
+ Seems to freeze up and hang around in task manager without properly exiting
+ Detaching cheat before closing the game means it works properly
+ Not sure what causes it.

**Comment by kwilcz** [comment]
Probably thanks to console being allocated.
I'll try to look for the solution for de-allocation for it when you exit the game.

**Comment by kwilcz** [comment]
Hmm, I now realized I have exactly the same code for detaching in my priv cheat and I never had an issue like that. Did it happen in a clean build?

**Comment by kwilcz** [comment]
Forgot to mention.
It's probably fixed in https://github.com/Wando1423/Antario/commit/3854c9e970b19b202b22386068f7a1ad93245eeb#diff-3142bd55d75223f4acc831acdde04ee7
Reopen a new issue if it will appear again.
