### ISSUE TITLE
menu in bounds issue

### ISSUE THREAD

**Issue by lm-ao** [kwilcz/Antario#33]
basically if you click close to the outside of the checkbox it will enable it, shouldn't it be only when clicked inside of it?

**Comment by lm-ao** [comment]
correction the check boxes will turn on if you click on the text that's beside them wouldn't that be a bug and if it's meant to be like that how would you fix it?

**Comment by Monsterxsync** [comment]
I don't know what way was intended but the "fix" for this is very simple just change it like this.
[https://github.com/Wando1423/Antario/pull/34](https://github.com/Wando1423/Antario/pull/34)

**Comment by kwilcz** [comment]
It was intended, checkbox selectable is so small that its much easier to use it that way.
I'll leave it for discussion maybe?

**Comment by Monsterxsync** [comment]
Played one game with only the checkboxes and it seems alright (after i got used it it).

**Comment by ghost** [comment]
It's Wando's decision, but the expected behaviour from a user would be that clicking the text activates the checkbox too. This is how it works on the web, and it can feel fiddly without it.

my 2c

**Comment by Monsterxsync** [comment]
For ease of use the old way works better yeah. I don't mind either way
though its a simple change maybe just leave a comment for new users and
they can decide?
