### ISSUE TITLE
box esp glitch

### ISSUE THREAD

**Issue by lm-ao** [kwilcz/Antario#35]
https://youtu.be/gcQQ1WNJ2Kc

basically if you pay close attention to the box when you move your mouse the outline part of it changes and offsets and becomes blurry then fucked up then normal

**Comment by kwilcz** [comment]
It's probably due to using floats as 2D screen coordinates. Try to use integers for it. I've made a class just to represent 2D coords.

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/02b0af28b3f24d106f1c43ab3a3dc880abfda187
