### ISSUE TITLE
Stream "proof" 

### ISSUE THREAD

**Issue by Monsterxsync** [kwilcz/Antario#38]
What exactly do you have to do to the present hook to make it not show on obs?

**Comment by kwilcz** [comment]
I think calling original present before drawing should be enough. Didn't test that tho.

**Comment by Monsterxsync** [comment]
Just tried that seemed to make it not show for me at all. but maybe im just doing it wrong.

**Comment by certmemer** [comment]
use the second present that steam overlay uses

**Comment by Monsterxsync** [comment]
Ok thanks, ill look into it.
