### ISSUE TITLE
Making a proper tab control?

### ISSUE THREAD

**Issue by WonderedWhy** [kwilcz/Antario#39]
How would I make a proper tab control?
What I want to do is take WindowX / TabAmount for the area, but have it create TabAmount of tabs. 
How do I go about this?

**Comment by kwilcz** [comment]
Will add in a future.

**Comment by AnonVodka** [comment]
Im not really familar with the Menu Framework, but how would you update the content of the child when switching tabs. I did my tabs like in imgui, where i change the value of an integer and depending on what the integer value is i draw diffrent stuff.

**Comment by kwilcz** [comment]
you just call Render for the tab children. If you set it as some kind of bool, you need to add some kind of TabID for your sections which will then render & gather info only if the TabID is active.

**Comment by WonderedWhy** [comment]
The only reason I ask is because I tried to use buttons, I even changed the buttons so they used ints, but it didn't change tab. I don't know how to make actual tab control, So I tried to use buttons

**Comment by AnonVodka** [comment]
Couldnt you just recall the render function everytime you press a tab button?

**Comment by WonderedWhy** [comment]
bump

**Comment by aethstetic** [comment]
you already got your answer?

**Comment by kwilcz** [comment]
Done with https://github.com/Wando1423/Antario/commit/3854c9e970b19b202b22386068f7a1ad93245eeb
