### ISSUE TITLE
Unhooking the cheat causes fps drops

### ISSUE THREAD

**Issue by HenkieHanker2** [kwilcz/Antario#41]
Hey,

i get like 20 fps when i unhooked the cheat, and if i try to close the cheat when i uninjected it will stay open  o,0. 

btw thanks for this  clean base. i learned a lot from it

Regards

**Comment by Monsterxsync** [comment]
Have you hooked something else and forgot to unhook it?

**Comment by HenkieHanker2** [comment]
nope i get it with the unmodified compiled version, btw im trying to hook paint traverse but i only get nullptr ;/

can you take a look here to see what causes the nullptr? https://github.com/HenkieHanker2/Antario thanks

**Comment by Monsterxsync** [comment]
Strange i don't get that issue on mine, hooking paint traverse is pretty straight forward. If you really need help doing it I'll add you on discord or something.

**Comment by HenkieHanker2** [comment]
sure, discord = WIllPill
#1560

**Comment by Monsterxsync** [comment]
Fixed for him on discord, can close.

**Comment by HenkieHanker2** [comment]
ye @Monsterxsync thanks for that, but the fps drop after unhooking is still there, after unhooking i can only close cs go with taskmanager

**Comment by Monsterxsync** [comment]
Try verify your csgo because I've referd people to this base and we all use the shutdown feature with no problems.

**Comment by HenkieHanker2** [comment]
k, then its probz me only ;/, again thanks for your time!

~Regards

**Comment by kwilcz** [comment]
Does it still happen? I had no issue and I'm using the same unhooking concept.

**Comment by HenkieHanker2** [comment]
no its fixed, i reinstalled windows and the cheat
