### ISSUE TITLE
Debug/release issue

### ISSUE THREAD

**Issue by Jujudo** [kwilcz/Antario#42]
The menu crash in debug mode but it works if i compile it as a release, why? it happens after "Draw manager initialized" has been outputted

**Comment by Monsterxsync** [comment]
Attach a debugger and see where it crashes?

**Comment by Jujudo** [comment]
I don't know how to attach a debugger.

**Comment by Monsterxsync** [comment]
Well you'll need to know to get much done. Visual studio has a debug tab (i think thats what its called im out cabt check) then select the option attach to process then attach it to csgo and wait for the crash to happen it will pause program execution where the crash happens.

**Comment by Jujudo** [comment]
Ok, error code "The thread 0x39380 has exited with code 1066991616 (0x3f990000).
The thread 0x39048 has exited with code 0 (0x0).
Exception thrown at 0x00000000 in csgo.exe: 0xC0000005: Access violation executing location 0x00000000."

**Comment by Monsterxsync** [comment]
It would have pointed you to what cause the crash.

**Comment by kwilcz** [comment]
Did you add anything? The code is ready to compile with no errors + tested. Shouldn't fuck up with anything.

**Comment by kwilcz** [comment]
Issue not reported by anyone else, closing.

**Comment by Jujudo** [comment]
It was my injector that made it crash, idk why.
