### ISSUE TITLE
Cheat unloading when Slider int is to big

### ISSUE THREAD

**Issue by AnonVodka** [kwilcz/Antario#43]
I dont know if its because i changed some things in the slider, but when i create a slider that goes from 0 to 1000 and i change the value to 0 in the slider the cheat unloads itself, i also cant unload it with the Detach function when the max value is 1000.

EDIT: i just realised that the whole cheat bugs out, every other slider doesnt work anymore, and the slider with the max value only works when on max

**Comment by kwilcz** [comment]
Weird thing, ill test that out later on. Possibly will rebuild menu schema so its easier to use anyway.

**Comment by kwilcz** [comment]
Closing, after alot of testing couldn't make it crash.
Open new issue if it will appear again.
