### ISSUE TITLE
Getting entity velocity crashes

### ISSUE THREAD

**Issue by ghost** [kwilcz/Antario#47]
I'm using the Netvar manager, doing this in the BaseEntity class:
```cpp
Vector GetVelocity()
{
	static int m_vecVelocity = g_pNetvars->GetOffset("DT_BasePlayer", "m_vecVelocity[0]");
        return GetValue<Vector>(m_vecVelocity);
}
```
crashes the game when reading.

**Comment by kwilcz** [comment]
It's because the proper prop for vecVelocity is ```DT_BasePlayer->localdata->m_vecVelocity[0]```
