### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by zef9** [kwilcz/Antario#49]
Hey, found an issue today, while making a second window in the menu. If you do a second BaseWindow (for Skinchanger for example) and you try to move it, it moves the window that gets called before it.
Basicly all i did was this:
`auto test = std::make_shared<BaseWindow>(Vector2D(200, 200), Vector2D(200, 200), g_Fonts.pFontTahoma8.get(), g_Fonts.pFontTahoma10.get(), "Antario - test");`
and call it after this->AddChild(windowMain);

Video of the issue: https://youtu.be/WUqN-OFAmF0

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/3385db067c462700b89035587ca3c3ee71be3d42
