### ISSUE TITLE
a slider issue

### ISSUE THREAD

**Issue by ghost** [kwilcz/Antario#50]
When your intial value is higher than flMaxValue, the slider will be like this
![20180819162753](https://user-images.githubusercontent.com/13448766/44306996-0b6b3a80-a3cd-11e8-8020-d1b3b71cfc49.png)

I know in most of the case this wont happen, but it should be fixed IMO.

**Comment by certmemer** [comment]
https://github.com/Wando1423/Antario/blob/master/Antario/GUI/GUI.cpp#L579
just add there some kind of flValue = std::clamp(flValue, flMinValue, flMaxValue) that should do the job
anyways menu is being reworked
