### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by sammy281** [kwilcz/Antario#54]
Is this project abandoned? I was looking forward to seeing the base updated with tabs, section names and other things.

Edit: I also noticed that ESP seems to flicker. Considering you properly set up everything with world to screen and viewmatrix I have no idea whats wrong.

**Comment by certmemer** [comment]
it's not, wando is just way too lazy to port the "proper" menu to antario
ill check the w2s

**Comment by sammy281** [comment]
I noticed it happens only when the entity is moving/jumping. It's temporarily solved by turning off multi-core rendering.

**Comment by kwilcz** [comment]
It is not abandoned, it's "paused" for now.

For filckering - try to use Integers instead of floats since d3d uses half-pixel coords (0.4 - lower coord, 0.6 - higher coord)

**Comment by kwilcz** [comment]
Base updated with new UI, closing.
