### ISSUE TITLE
I can't make ComboBox... tried fixing it but it's missing something

### ISSUE THREAD

**Issue by bogdan-velicu** [kwilcz/Antario#56]
I've uncommented everything that needed to be to work but still no result. I know this project is dead but it's really the best source I could find beginner friendly ... right now I'm learning to draw / Esp stuff then I can step up to aimbot and other stuff. So conclusion can you please do something about the source so I can at least use the menu properly ? Thank you for reading this !

**Comment by certmemer** [comment]
how is it dead if the menu has been recoded a week ago

**Comment by bogdan-velicu** [comment]
Well, part of the menu has been recoded and some old stuff was deleted and he says he is going to rework those... do you even use this source cause you said it should be working but it's not and I'm really willing to learn something not just ctrl + c && ctrl + v so yeah ...

**Comment by kwilcz** [comment]
Added ComboBox support with https://github.com/Wando1423/Antario/commit/8fd7e863afd381cea2fbbd640cc02f624d1ce5dd

Closing.
