### ISSUE TITLE
Tab positioning and disappearing

### ISSUE THREAD

**Issue by kwilcz** [kwilcz/Antario#62]
"this tab positioning glitch seen on the 'rage' tab and the 'other' tab
http://prntscr.com/lvsz30

also after the scrollbar update the other tabs appeared invisible when i was in the 'rage' (the 1st tab). unsure what is causing this. any help would be appreciated.
http://prntscr.com/lvt0xi"

**Comment by ZeroXKiritsu** [comment]
try this in tab constructor, maybe u render scrollball first and second render childs
g_Render.SetCustomScissorRect(this->rcBoundingBox);
    {
        this->RenderChildObjects();
        scrollBar->Render();
    }
    g_Render.RestoreOriginalScissorRect();

**Comment by slack2450** [comment]
Quick fix:

Comment out:
`g_Render.SetCustomScissorRect(vpCombo);`
and
`g_Render.RestoreOriginalScissorRect();`

in
`void ComboBox::Render()`
in 
`GUI.cpp`

**Comment by kwilcz** [comment]
fixed with https://github.com/Wando1423/Antario/commit/045e0f9d93bf6400ce8162284bf881de16a89f71
ty babe
