### ISSUE TITLE
3 problems

### ISSUE THREAD

**Issue by MaximWizard** [kwilcz/Antario#66]
A menu will appear in the upper left corner, besides all the weapons on which there are skins-black become

**Comment by minot0r** [comment]
In `GUI.cpp` line 225
change : `UIObject::SetPos(g_Render.GetScreenCenter() - (szSize * .5f));`
to : `UIObject::SetPos(g_Render.GetScreenCenter());`
this will fix your first problem
you're welcome ;)

**Comment by MaximWizard** [comment]
snk )
as creat cheat on aiming?
I wanna... but not good understand  your code and all him specific areas
(((
You nice man)))
You wrote it from scratch????

**Comment by slack2450** [comment]
You want to iterate through the entity list, a good example is [here](https://github.com/AimTuxOfficial/AimTux/blob/master/src/Hacks/aimbot.cpp). Not a specific issue to this cheat though, you'd be better looking up these somewhere else.

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/4d0e73c77d3e7dae60843966ae6395512d4dec7b, https://github.com/Wando1423/Antario/commit/faa0c68d136ad574a18dc6f8732729d70edb3bd5.
