### ISSUE TITLE
weird behavior with sections

### ISSUE THREAD

**Issue by cust0me** [kwilcz/Antario#67]
![ezgif-1-0ae2b289da21](https://user-images.githubusercontent.com/44414980/50551555-4b470600-0c7a-11e9-8fc8-e1ce9e5ed512.gif)

**Comment by kwilcz** [comment]
Will fix shortly, for quick fix:
https://github.com/Wando1423/Antario/blob/master/Antario/GUI/GUI.cpp#L180
Change
` if (object->GetBBox().ContainsPoint(ptPoint))` to ` if (object->GetBBox().ContainsPoint(ptPoint) && object->IsVisible)`

**Comment by cust0me** [comment]
UIObject class can not access anything from the Control class, and when i try and use std::dynamic_pointer_cast<Control> on any UIObject item, it results in a crash.

**Comment by kwilcz** [comment]
Will push the fix after the weekend, with all of the other ones.

**Comment by cust0me** [comment]
Thanks

**Comment by cust0me** [comment]
Any eta on the fixes?

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/1b69632d6e2c1ba5d659083e6b58f7e9afa55cd5.
