### ISSUE TITLE
possibility code bugs in GUI

### ISSUE THREAD

**Issue by anarh1st47** [kwilcz/Antario#69]
https://github.com/Wando1423/Antario/blob/faa0c68d136ad574a18dc6f8732729d70edb3bd5/Antario/GUI/GUI.cpp#L1237 this if always true(cuz placed in case WM_MOUSEMOVE)

https://github.com/Wando1423/Antario/blob/faa0c68d136ad574a18dc6f8732729d70edb3bd5/Antario/GUI/GUI.cpp#L401 probably here should be "break;" after this line?

https://github.com/Wando1423/Antario/blob/faa0c68d136ad574a18dc6f8732729d70edb3bd5/Antario/GUI/GUI.cpp#L461 missing break?

https://github.com/Wando1423/Antario/blob/faa0c68d136ad574a18dc6f8732729d70edb3bd5/Antario/GUI/GUI.cpp#L1288 same, but with return true?

**Comment by kwilcz** [comment]
Fixed them all, thanks bud 👍
