### ISSUE TITLE
Text not rendered (block characters)

### ISSUE THREAD

**Issue by ghost** [kwilcz/Antario#72]
I think it worked initially when i compiled it but it doesent seem to be working now: https://i.imgur.com/irdW21j.jpg
I am using the default font settings. The draw manager logs say everything is going well.
`auto mainWindow = std::make_shared<Window>("Antario - Main", SSize(802, 577), g_Fonts.pFontTahoma8, g_Fonts.pFontTahoma10);
`
Any ideas?
*Edit: It works after I enabled multicore, still doesent work with it disabled tho.

**Comment by kwilcz** [comment]
enable multicore rendering
