### ISSUE TITLE
How to put the type of armor?

### ISSUE THREAD

**Issue by MaximWizard** [kwilcz/Antario#73]
```
"If there is helmet, then 1 if there is no helmet the 0"
should work like this

> bool GetArmour2()
> 	{
> 		static auto m_iArmH = g_pNetvars->GetOffset("DT_CSPlayer", "m_bHasHeavyArmor");
> 		return GetValue<BYTE>(m_iArmH);
> 	}

```
Always return true
what's the problem???
I'm sorry for my very bad english language...  :(

**Comment by certmemer** [comment]
static auto m_bHasHelmet = g_pNetvars->GetOffset("DT_CSPlayer", "m_bHasHelmet");
return GetValue<bool>(m_bHasHelmet);
