### ISSUE TITLE
No menu drawn without FPS Counter

### ISSUE THREAD

**Issue by jellythedoge** [kwilcz/Antario#8]
https://gyazo.com/41434633005436af16f8c21a165035d2
https://gyazo.com/fa6e974ebe0083f5fddbf1c5fd9d44fa

**Comment by kwilcz** [comment]
Check out now. I didn't test it but should be enough. CSGO has some retarded stateblock settings which are set properly only when you're using net_graph / fps counter / game console etc.
https://github.com/Wando1423/Antario/blob/master/Antario/Hooks.cpp#L126
