### ISSUE TITLE
Antario Crash After Died.

### ISSUE THREAD

**Issue by vilesis** [kwilcz/Antario#81]
```
Exception thrown: read access violation.
**this** was 0x11130BC. occurred
```

```
    T GetValue(const int offset)
    {
        **return *reinterpret_cast<T*>(reinterpret_cast<std::uintptr_t>(this) + offset);**
    }
```

**Comment by vilesis** [comment]
This is In CEntity.h

**Comment by vilesis** [comment]
![image](https://user-images.githubusercontent.com/48322198/53960530-4d3ba400-40c5-11e9-9cf6-14486be8bd37.png)

**Comment by vilesis** [comment]
Another Crash: Exception thrown at 0x248ECD50 (client_panorama.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x0000002A. occurred


![image](https://user-images.githubusercontent.com/48322198/53975693-3a849780-40e4-11e9-86fc-f2de0964a352.png)
![image](https://user-images.githubusercontent.com/48322198/53975733-4ec89480-40e4-11e9-88c6-42a8328049b5.png)

**Comment by vilesis** [comment]
```
void __stdcall Hooks::FrameStageNotify(ClientFrameStage_t curStage)
{
	//static auto oFrameStage = g_Hooks.pClientHook->GetOriginal<FrameStageNotify_t>(vtable_indexes::frameStage);

	//if (!Shonax.Visuals.drawteaserrange)
	{
		g_Misc.sv_cheats_spoof(curStage);
		g_Misc.ThirdPerson(curStage);
		g_Misc.KnifeCustom(curStage);
		if (curStage == FRAME_NET_UPDATE_POSTDATAUPDATE_START)
			skinchanger();//ez
			
		
			
		g_Misc.SoundEsp(curStage);

		if (curStage == FRAME_RENDER_START)
		{
			g_Misc.remose_flash();
			g_Misc.remove_smoke();
			g_Misc.ragdol_start();
		}

		g_Resolver.FrameStage(curStage);
	}
	

	oFrameStageNotify_t->GetTrampoline()(curStage);
}
```

**Comment by vilesis** [comment]
in final }

**Comment by kwilcz** [comment]
Doesnt look like antarios hooking system at all, so thats probably a reason why it crashes...

**Comment by GitLinker** [comment]
> Doesnt look like antarios hooking system at all, so thats probably a reason why it crashes...

It is Antario, though it's a paste of StickRpgHook
StickRpg Used Antario

Shonax (Russian Paster, claims to know how to code) made a paste off of it
(Every paste Shonax makes, crashes)

The original author of this issue, stop using paste of paste
Especially Russian Paste
