### ISSUE TITLE
netchannel_hook Please 

### ISSUE THREAD

**Issue by Spangonagornomb** [kwilcz/Antario#83]
hello can you please add netchannel_hook ? 

thanks!

**Comment by Spangonagornomb** [comment]
Sorry i just couldnt find a way to hook since you need to hook it from Createmove

**Comment by kwilcz** [comment]
get clientmode->netchannel and thats it, where is the problem?

I'm not adding any more features / hooks to keep out from some more detection vectors for begginer coders.
