### ISSUE TITLE
 "Fix crashes when CSWpnData" bad fix?

### ISSUE THREAD

**Issue by ritalinaddict** [kwilcz/Antario#84]
I don't see a reason to loop & backup every player when a much better fix was already posted in an antario thread (and has been around in general for ages) 
https://www.unknowncheats.me/forum/counterstrike-global-offensive/231080-getting-wpndata-vtable-indexes.html

ive been using it for a fair while now and have had 0 crashes while using a whole slew of weapon related esps in preset

**Comment by slack2450** [comment]
Crashed a bunch on me couldn't make it through a whole deathmatch without a crash. If you've got a signature it's a simple swap to that interface.

**Comment by kwilcz** [comment]
Changed to the one from forums, the less global pointers the better.
Will reopen if some issues will occur.
