### ISSUE TITLE
Menu Text 

### ISSUE THREAD

**Issue by autumnhvh** [kwilcz/Antario#92]
Text is messed up somehow. Didn't know how to fix it
![image](https://user-images.githubusercontent.com/49427815/55852349-d48f9380-5b19-11e9-8460-57de541d8a9b.png)

**Comment by kwilcz** [comment]
Disable multisampling for now.

**Comment by autumnhvh** [comment]
> Disable multisampling for now.

I'll try it. Thanks for the quick responce.
