### ISSUE TITLE
antario doesnt work after an update

### ISSUE THREAD

**Issue by AdNine87** [kwilcz/Antario#94]
So antario just doesnt work it crashes. I tried downloading unmodified antario still no luck and debuger doesnt catch any exceptions.

**Comment by jugi-dev** [comment]
weird. my cheat works fine and uses antario as base.

**Comment by AdNine87** [comment]
Can you please try downloading antario and seeing if it works? (Without any modifications)

**Comment by tim180** [comment]
its because that d3dx9 stuff is now enabled just use this as fix in csgo start parametars -disable_d3d9ex

**Comment by JimmyBassy** [comment]
Yeah is there any way to actually fix the base without putting the disable_d3d9ex, beacuse at some point they will remove this launch option as they did with panorama

**Comment by tim180** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/332751-update.html here.

**Comment by kwilcz** [comment]
Fixed with https://github.com/Wando1423/Antario/commit/84cbab995746db8e637dff0e12d31662eae669d4.
