### ISSUE TITLE
How to edit CVars with this base

### ISSUE THREAD

**Issue by JimmyBassy** [kwilcz/Antario#95]
I would like to know how can I edit Cvars with this base and if it's not possible what do I have to add to get a CVar editor/modifier. Btw very nice base I'm learning a lot with it! Thank you!

**Comment by pauloabreu** [comment]
1º You need add the **ICVar** class to your SDK folder

2º Capture the interface in **interface.cpp** 
`g_pCvar = CaptureInterface<ICVar>("vstdlib.dll", "VEngineCvar007");`

3º usage example:
`ConVar* sv_grenadepreview = g_pCvar->FindVar("cl_grenadepreview");
sv_grenadepreview->SetValue(1);`


[ICvar.zip](https://github.com/Wando1423/Antario/files/3730380/ICvar.zip)

**Comment by JimmyBassy** [comment]
Thanks dude!
